### ISSUE TITLE
Link for all files not working

### ISSUE THREAD

**Issue by nmattei** [PrefLib/contribution#6]
Hope you're doing well. I'm a graduate student working in computational social choice and I wanted to let you know that PrefLib has always been an important resource for me. 

I noticed that the website recently went through an overhaul with a more modern and comprehensive look. However, I noticed that the 'download all the ... data files' buttons for different types of data files are not working. I'm talking about the buttons in this page-
https://www.preflib.org/data/types

Hope this helps in making the website work better. The download all option, if it works, would really be helpful to researchers like me.

**Comment by Simon-Rey** [comment]
Fixed.
